### ISSUE TITLE
Highlight Code Snippets

### ISSUE THREAD

**Issue by carlosazaustre** [carlosazaustre/devask#20]
Questions and Answers with code snippets are not highlighting

<img width="1352" alt="image" src="https://github.com/user-attachments/assets/b09a71a1-4c60-49e6-ab00-1c43d6dde7c0">

**Comment by marta-vilaseca** [comment]
Hi, can I try to take care of this one @carlosazaustre? Gracias! 😃

**Comment by carlosazaustre** [comment]
Todo tuyo! :)
